"""Initial migration.

Revision ID: 614a5576040f
Revises: a50cde241c4b
Create Date: 2023-09-20 11:06:59.607762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614a5576040f'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baked_goods', sa.Column('name', sa.String(), nullable=True))
    op.add_column('baked_goods', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('baked_goods', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('baked_goods', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('baked_goods', sa.Column('bakery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', 'bakeries', ['bakery_id'], ['id'])
    op.add_column('bakeries', sa.Column('name', sa.String(), nullable=True))
    op.add_column('bakeries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('bakeries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'updated_at')
    op.drop_column('bakeries', 'created_at')
    op.drop_column('bakeries', 'name')
    op.drop_constraint(op.f('fk_baked_goods_bakery_id_bakeries'), 'baked_goods', type_='foreignkey')
    op.drop_column('baked_goods', 'bakery_id')
    op.drop_column('baked_goods', 'updated_at')
    op.drop_column('baked_goods', 'created_at')
    op.drop_column('baked_goods', 'price')
    op.drop_column('baked_goods', 'name')
    # ### end Alembic commands ###
